import '../domain/entities.dart';

class DummyData {
  DummyData._();

  static final List<FarmField> lahanList = [
    const FarmField(id: 'f1', nama: 'Greenhouse Belakang', deskripsi: 'Greenhouse 6x4m', lokasi: 'Halaman belakang'),
    const FarmField(id: 'f2', nama: 'Sawah Blok A', deskripsi: 'Lahan sawah 500m²', lokasi: 'Desa Sukamaju'),
    const FarmField(id: 'f3', nama: 'Pot Balkon', deskripsi: 'Urban farming di balkon', lokasi: 'Lantai 3'),
  ];

  static final List<Crop> cropList = [
    Crop(
      id: 'c1',
      nama: 'Cabai Kloter 1',
      jenisTanaman: 'Cabai Rawit',
      varietas: 'Rawit Hijau',
      namaLahan: 'Greenhouse Belakang',
      lokasiPlot: 'Plot A-1',
      tanggalSemai: DateTime.now().subtract(const Duration(days: 58)),
      tanggalTanam: DateTime.now().subtract(const Duration(days: 45)),
      estimasiPanen: DateTime.now().add(const Duration(days: 32)),
      durasiHariPanen: 90,
      healthStatus: CropHealthStatus.sehat,
      lifecycleStatus: CropLifecycleStatus.generatif,
      tinggiBatang: 45,
      jumlahDaun: 32,
      fotoTimeline: [],
      createdAt: DateTime.now().subtract(const Duration(days: 58)),
      updatedAt: DateTime.now(),
    ),
    Crop(
      id: 'c2',
      nama: 'Tomat Cherry',
      jenisTanaman: 'Tomat',
      varietas: 'Cherry Red',
      namaLahan: 'Pot Balkon',
      lokasiPlot: 'Pot 3',
      tanggalSemai: DateTime.now().subtract(const Duration(days: 30)),
      tanggalTanam: DateTime.now().subtract(const Duration(days: 20)),
      estimasiPanen: DateTime.now().add(const Duration(days: 45)),
      durasiHariPanen: 75,
      healthStatus: CropHealthStatus.sehat,
      lifecycleStatus: CropLifecycleStatus.vegetatif,
      tinggiBatang: 25,
      jumlahDaun: 18,
      fotoTimeline: [],
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now(),
    ),
    Crop(
      id: 'c3',
      nama: 'Selada Romaine',
      jenisTanaman: 'Selada',
      varietas: 'Romaine',
      namaLahan: 'Greenhouse Belakang',
      lokasiPlot: 'Plot B-2',
      tanggalSemai: DateTime.now().subtract(const Duration(days: 20)),
      estimasiPanen: DateTime.now().add(const Duration(days: 10)),
      durasiHariPanen: 30,
      healthStatus: CropHealthStatus.hamaPenyakit,
      lifecycleStatus: CropLifecycleStatus.vegetatif,
      tinggiBatang: 15,
      jumlahDaun: 12,
      fotoTimeline: [],
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now(),
    ),
    Crop(
      id: 'c4',
      nama: 'Kangkung Segar',
      jenisTanaman: 'Kangkung',
      varietas: 'Darat',
      namaLahan: 'Sawah Blok A',
      lokasiPlot: 'Petak 1',
      tanggalSemai: DateTime.now().subtract(const Duration(days: 18)),
      estimasiPanen: DateTime.now().add(const Duration(days: 7)),
      durasiHariPanen: 25,
      healthStatus: CropHealthStatus.sehat,
      lifecycleStatus: CropLifecycleStatus.vegetatif,
      tinggiBatang: 20,
      jumlahDaun: 24,
      fotoTimeline: [],
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now(),
    ),
    Crop(
      id: 'c5',
      nama: 'Basil Italia',
      jenisTanaman: 'Basil',
      varietas: 'Sweet Basil',
      namaLahan: 'Pot Balkon',
      lokasiPlot: 'Pot 5',
      tanggalSemai: DateTime.now().subtract(const Duration(days: 22)),
      estimasiPanen: DateTime.now().add(const Duration(days: 8)),
      durasiHariPanen: 30,
      healthStatus: CropHealthStatus.sehat,
      lifecycleStatus: CropLifecycleStatus.generatif,
      tinggiBatang: 18,
      jumlahDaun: 28,
      fotoTimeline: [],
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<DailyTask> todayTasks = [
    DailyTask(
      id: 't1',
      cropId: 'c1',
      cropNama: 'Cabai Kloter 1',
      deskripsi: 'Penyiraman pagi',
      tipe: ActivityType.penyiraman,
      jadwal: DateTime.now(),
    ),
    DailyTask(
      id: 't2',
      cropId: 'c1',
      cropNama: 'Cabai Kloter 1',
      deskripsi: 'Pemupukan Minggu ke-8 (NPK)',
      tipe: ActivityType.pemupukan,
      jadwal: DateTime.now(),
    ),
    DailyTask(
      id: 't3',
      cropId: 'c3',
      cropNama: 'Selada Romaine',
      deskripsi: 'Cek kondisi hama kutu daun',
      tipe: ActivityType.pestisida,
      jadwal: DateTime.now(),
    ),
    DailyTask(
      id: 't4',
      cropId: 'c2',
      cropNama: 'Tomat Cherry',
      deskripsi: 'Penyiraman sore',
      tipe: ActivityType.penyiraman,
      jadwal: DateTime.now(),
      selesai: true,
    ),
    DailyTask(
      id: 't5',
      cropId: 'c4',
      cropNama: 'Kangkung Segar',
      deskripsi: 'Penyiangan gulma',
      tipe: ActivityType.penyiangan,
      jadwal: DateTime.now(),
    ),
  ];

  static final List<HarvestResult> harvestHistory = [
    HarvestResult(
      id: 'h1',
      cropId: 'h_c1',
      tanggalPanen: DateTime.now().subtract(const Duration(days: 30)),
      beratKg: 15.5,
      jumlahBuah: 200,
      kualitas: 'Bagus',
      hargaJualPerKg: 45000,
      rating: 5,
      catatan: 'Panen pertama sangat memuaskan',
    ),
    HarvestResult(
      id: 'h2',
      cropId: 'h_c2',
      tanggalPanen: DateTime.now().subtract(const Duration(days: 60)),
      beratKg: 8.0,
      kualitas: 'Sedang',
      hargaJualPerKg: 35000,
      rating: 3,
      catatan: 'Terkena hama di minggu ke-6',
    ),
    HarvestResult(
      id: 'h3',
      cropId: 'h_c3',
      tanggalPanen: DateTime.now().subtract(const Duration(days: 90)),
      beratKg: 20.0,
      jumlahBuah: 300,
      kualitas: 'Bagus',
      hargaJualPerKg: 50000,
      rating: 4,
    ),
  ];

  static final List<FarmReminder> reminders = [
    FarmReminder(
      id: 'r1',
      cropId: 'c1',
      judul: 'Pemupukan Cabai Kloter 1',
      deskripsi: 'Berikan pupuk NPK 5 gram per tanaman',
      waktu: DateTime.now().add(const Duration(hours: 2)),
      isOtomatis: true,
    ),
    FarmReminder(
      id: 'r2',
      cropId: 'c3',
      judul: 'Cek Hama Selada',
      deskripsi: 'Periksa daun untuk kutu daun',
      waktu: DateTime.now().add(const Duration(hours: 6)),
      isOtomatis: true,
    ),
    FarmReminder(
      id: 'r3',
      cropId: 'c4',
      judul: 'Persiapan Panen Kangkung',
      deskripsi: 'Kangkung siap panen dalam 7 hari',
      waktu: DateTime.now().add(const Duration(days: 5)),
      isOtomatis: true,
    ),
    FarmReminder(
      id: 'r4',
      judul: 'Beli Pupuk Organik',
      deskripsi: 'Stok pupuk hampir habis',
      waktu: DateTime.now().add(const Duration(days: 2)),
    ),
  ];

  static List<ActivityLog> activityLogs = [
    ActivityLog(
      id: 'a1',
      cropId: 'c1',
      tipe: ActivityType.penyiraman,
      tanggal: DateTime.now().subtract(const Duration(days: 1)),
      catatan: 'Penyiraman normal',
    ),
    ActivityLog(
      id: 'a2',
      cropId: 'c1',
      tipe: ActivityType.pemupukan,
      tanggal: DateTime.now().subtract(const Duration(days: 2)),
      jenisPupuk: 'NPK',
      dosisPupuk: 5.0,
      catatan: 'Pemupukan rutin minggu ke-7',
    ),
    ActivityLog(
      id: 'a3',
      cropId: 'c3',
      tipe: ActivityType.pestisida,
      tanggal: DateTime.now().subtract(const Duration(days: 1)),
      jenisPestisida: 'Neem Oil',
      konsentrasi: 5.0,
      statusKesehatan: CropHealthStatus.hamaPenyakit,
      catatan: 'Ditemukan kutu daun pada daun bagian bawah',
    ),
    ActivityLog(
      id: 'a4',
      cropId: 'c1',
      tipe: ActivityType.lainnya,
      tanggal: DateTime.now().subtract(const Duration(days: 3)),
      catatan: 'Daun sedikit menguning, kemungkinan kekurangan nitrogen',
      statusKesehatan: CropHealthStatus.sehat,
      tinggiBatang: 42,
      jumlahDaun: 30,
    ),
  ];
}
